### ISSUE TITLE
test.py, roi_align

### ISSUE THREAD

**Issue by Abdulazizbek** [chenjun2hao/FOTS.pytorch#3]
Great repo. I'm trying to test with pretrained model.
But I got this error:
```
Alex:~/Alex/OCR/FOTS.pytorch$ python test.py
make: Entering directory 'Alex/OCR/FOTS.pytorch/nms'
make: 'adaptor.so' is up to date.make: Leaving directory '
Alex/OCR/FOTS.pytorch/nms
Traceback (most recent call last):  File "test.py", line 21, in <module>
    from src.utils import strLabelConverter, alphabet  File "Alex/OCR/FOTS.pytorch/src/utils.py", line 24, in <module>
    from rroi_align.modules.rroi_align import _RRoiAlign  File "Alex/OCR/FOTS.pytorch/rroi_align/modules/rroi_align.py", line 2, in <module>
    from ..functions.rroi_align import RRoiAlignFunction  File "Alex/OCR/FOTS.pytorch/rroi_align/functions/rroi_align.py", line 3, in <module>
    from .._ext import rroi_alignImportError: No module named 'rroi_align._ext'
Alex:~/Alex/OCR/FOTS.pytorch$ 
```

**from .._ext import rroi_alignImportError: No module named 'rroi_align._ext**

Here, what is `_ext`  stands for

python 3.5.2
Thank you beforehand.

**Comment by hufangjian** [comment]
the same issue

**Comment by chenjun2hao** [comment]
> Great repo. I'm trying to test with pretrained model.
> But I got this error:
> 
> ```
> Alex:~/Alex/OCR/FOTS.pytorch$ python test.py
> make: Entering directory 'Alex/OCR/FOTS.pytorch/nms'
> make: 'adaptor.so' is up to date.make: Leaving directory '
> Alex/OCR/FOTS.pytorch/nms
> Traceback (most recent call last):  File "test.py", line 21, in <module>
>     from src.utils import strLabelConverter, alphabet  File "Alex/OCR/FOTS.pytorch/src/utils.py", line 24, in <module>
>     from rroi_align.modules.rroi_align import _RRoiAlign  File "Alex/OCR/FOTS.pytorch/rroi_align/modules/rroi_align.py", line 2, in <module>
>     from ..functions.rroi_align import RRoiAlignFunction  File "Alex/OCR/FOTS.pytorch/rroi_align/functions/rroi_align.py", line 3, in <module>
>     from .._ext import rroi_alignImportError: No module named 'rroi_align._ext'
> Alex:~/Alex/OCR/FOTS.pytorch$ 
> ```
> 
> **from .._ext import rroi_alignImportError: No module named 'rroi_align._ext**
> 
> Here, what is `_ext` stands for
> 
> python 3.5.2
> Thank you beforehand.

That's a custom pytorch extension,this project is laying on python0.4.1,
